r"""
Video 226: Cyclotomic Fields — Advanced Abstract Algebra

Roots of unity, cyclotomic polynomials, cyclotomic extensions,
Galois groups (Z/nZ)*, applications to constructibility.

Follows v2 template quality rules.
"""

from manim import *
import sys, os
_template_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "templates"))
if _template_dir not in sys.path:
    sys.path.insert(0, _template_dir)
from channel_branding import (
    BG, PRIMARY, SECONDARY, ACCENT, RED, DIM, WHITE, SANS, MONO,
    TITLE_SIZE, HEADING_SIZE, BODY_SIZE, LABEL_SIZE, FAST, NORMAL, SLOW,
    play_intro, play_outro, setup_background,
)
from layout import LayoutEngine, ensure_fits


class Video226_CyclotomicFields(Scene):

    def construct(self):
        self.camera.background_color = BG
        self.ly = LayoutEngine(self)
        self._bg_dots, self._bg_gradient = setup_background(self)

        self.scene1_hook()
        self.scene2_primitive_roots()
        self.scene3_cyclotomic_polynomials()
        self.scene4_extensions()
        self.scene5_galois_groups()
        self.scene6_applications()
        self.scene7_connection_abel_ruffini()
        self.scene8_summary()

    def scene1_hook(self):
        self.add_subcaption(
            "The solutions to x to the n equals 1 are called the n-th roots of unity. "
            "On the complex plane, they sit perfectly spaced on the unit circle, "
            "forming a regular n-gon. The field generated by these roots "
            "is called a cyclotomic field.",
            duration=14,
        )
        play_intro(self, "Cyclotomic Fields", "Advanced Abstract Algebra")

        title = self.ly.title("Roots of Unity")

        # Draw unit circle
        circle = Circle(radius=2, color=DIM, stroke_width=2)
        self.ly.center_in_content(circle)
        self.play(Create(circle), run_time=NORMAL)
        self.wait(2)

        # Plot 8th roots of unity
        n = 8
        dots = VGroup()
        for k in range(n):
            angle = 2 * PI * k / n - PI / 2
            dot = Dot(
                2 * RIGHT * np.cos(angle) + 2 * UP * np.sin(angle),
                radius=0.08, color=ACCENT,
            )
            dots.add(dot)
        self.play(FadeIn(dots), run_time=NORMAL)
        self.wait(3)

        items = [
            Text("x^n = 1 has n solutions on the unit circle",
                 font_size=BODY_SIZE, color=WHITE, font=SANS),
            Text("Q(zeta_n): the cyclotomic field",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Beautiful structure: Galois groups, number theory",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
        ]
        # Place items to the right of the circle
        for item in items:
            self.ly.safe_place(item, RIGHT, anchor=circle, buff=0.5)
        self.ly.progressive_reveal(items, start_from=title)
        self.wait(4)
        self.ly.clear()

    def scene2_primitive_roots(self):
        self.add_subcaption(
            "A primitive n-th root of unity is one that is not a k-th root "
            "for any proper divisor k of n. There are exactly phi of n "
            "primitive roots, where phi is Euler's totient function. "
            "The standard primitive root is zeta sub n equals e to the 2 pi i over n.",
            duration=16,
        )
        self.ly.section_divider(1, "Roots of Unity")
        title = self.ly.title("Primitive Roots of Unity")

        zeta = MathTex(
            r"\zeta_n = e^{2\pi i / n}",
            font_size=HEADING_SIZE, color=ACCENT,
        )
        self.ly.safe_place(zeta, DOWN, anchor=title, buff=0.4)
        self.play(Write(zeta), run_time=NORMAL)
        self.wait(3)

        items = [
            Text("Primitive: zeta^k != 1 for all 1 <= k < n",
                 font_size=BODY_SIZE, color=WHITE, font=SANS),
            Text("Exactly phi(n) primitive n-th roots",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Example: zeta_6 = e^{2pi i/6} is primitive",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
            Text("But e^{2pi i/3} is NOT primitive for n=6",
                 font_size=BODY_SIZE, color=RED, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=zeta)
        self.wait(5)
        self.ly.clear()

    def scene3_cyclotomic_polynomials(self):
        self.add_subcaption(
            "The n-th cyclotomic polynomial is the product of x minus zeta "
            "over all primitive n-th roots. It has integer coefficients. "
            "Key identity: x to the n minus 1 equals the product of Phi sub d "
            "over all divisors d of n. Every Phi sub n is irreducible over Q.",
            duration=16,
        )
        self.ly.section_divider(2, "Cyclotomic Polynomials")
        title = self.ly.title("The n-th Cyclotomic Polynomial")

        defn = MathTex(
            r"\Phi_n(x) = \prod_{\substack{\zeta^n = 1 \\ \zeta \text{ primitive}}} (x - \zeta)",
            font_size=HEADING_SIZE, color=PRIMARY,
        )
        boxed = self.ly.formula_box(defn, PRIMARY)
        self.ly.safe_place(boxed, DOWN, anchor=title, buff=0.4)
        self.play(Write(defn), run_time=NORMAL)
        self.wait(4)
        self.play(FadeOut(boxed), run_time=FAST)

        identity = MathTex(
            r"x^n - 1 = \prod_{d | n} \Phi_d(x)",
            font_size=HEADING_SIZE, color=SECONDARY,
        )
        self.ly.safe_place(identity, DOWN, anchor=title, buff=0.4)
        self.play(Write(identity), run_time=NORMAL)
        self.wait(3)
        self.play(FadeOut(identity), run_time=FAST)

        examples = [
            MathTex(r"\Phi_1 = x - 1", font_size=BODY_SIZE, color=WHITE),
            MathTex(r"\Phi_2 = x + 1", font_size=BODY_SIZE, color=WHITE),
            MathTex(r"\Phi_3 = x^2 + x + 1", font_size=BODY_SIZE, color=WHITE),
            MathTex(r"\Phi_4 = x^2 + 1", font_size=BODY_SIZE, color=SECONDARY),
            MathTex(r"\Phi_6 = x^2 - x + 1", font_size=BODY_SIZE, color=SECONDARY),
        ]
        self.ly.progressive_reveal(examples, start_from=title)
        self.wait(5)
        self.ly.clear()

    def scene4_extensions(self):
        self.add_subcaption(
            "The n-th cyclotomic field is Q of zeta sub n. "
            "Since Phi sub n is irreducible with degree phi of n, "
            "the extension degree is phi of n. "
            "Cyclotomic extensions are always Galois.",
            duration=12,
        )
        self.ly.section_divider(3, "Cyclotomic Extensions")
        title = self.ly.title("Cyclotomic Extensions")

        items = [
            MathTex(r"\mathbb{Q}(\zeta_n) / \mathbb{Q} \text{ has degree } \varphi(n)",
                    font_size=HEADING_SIZE, color=PRIMARY),
            MathTex(r"[\mathbb{Q}(\zeta_5) : \mathbb{Q}] = \varphi(5) = 4",
                    font_size=BODY_SIZE, color=WHITE),
            MathTex(r"[\mathbb{Q}(\zeta_8) : \mathbb{Q}] = \varphi(8) = 4",
                    font_size=BODY_SIZE, color=WHITE),
            Text("Always Galois (splitting field of x^n - 1)",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=title)
        self.wait(5)
        self.ly.clear()

    def scene5_galois_groups(self):
        self.add_subcaption(
            "The Galois group of Q of zeta sub n over Q is isomorphic to "
            "the multiplicative group of integers modulo n. "
            "Each element sends zeta sub n to zeta sub n to the k-th power. "
            "For prime p, the group is cyclic of order p minus 1.",
            duration=16,
        )
        self.ly.section_divider(3, "Galois Groups")
        title = self.ly.title("Gal(Q(zeta_n)/Q)")

        thm = MathTex(
            r"\text{Gal}(\mathbb{Q}(\zeta_n)/\mathbb{Q}) \cong (\mathbb{Z}/n\mathbb{Z})^\times",
            font_size=HEADING_SIZE, color=ACCENT,
        )
        boxed = self.ly.formula_box(thm, ACCENT)
        self.ly.safe_place(boxed, DOWN, anchor=title, buff=0.4)
        self.play(Write(thm), run_time=NORMAL)
        self.wait(3)
        self.play(FadeOut(boxed), run_time=FAST)

        action = MathTex(
            r"\sigma_k : \zeta_n \mapsto \zeta_n^k",
            font_size=HEADING_SIZE, color=PRIMARY,
        )
        self.ly.safe_place(action, DOWN, anchor=title, buff=0.4)
        self.play(Write(action), run_time=NORMAL)
        self.wait(3)
        self.play(FadeOut(action), run_time=FAST)

        examples = [
            MathTex(r"n=5: \text{Gal} \cong C_4 \text{ (cyclic)}",
                    font_size=BODY_SIZE, color=WHITE),
            MathTex(r"n=8: \text{Gal} \cong C_2 \times C_2",
                    font_size=BODY_SIZE, color=WHITE),
            MathTex(r"n=p: \text{Gal} \cong C_{p-1} \text{ (always cyclic)}",
                    font_size=BODY_SIZE, color=SECONDARY),
        ]
        self.ly.progressive_reveal(examples, start_from=title)
        self.wait(5)
        self.ly.clear()

    def scene6_applications(self):
        self.add_subcaption(
            "Cyclotomic fields have deep applications. A regular n-gon is "
            "constructible if and only if phi of n is a power of 2. "
            "Gauss proved the 17-gon is constructible. They also connect to "
            "quadratic reciprocity and Fermat's last theorem.",
            duration=16,
        )
        self.ly.section_divider(4, "Applications")
        title = self.ly.title("Applications of Cyclotomic Fields")

        items = [
            Text("Constructibility: regular n-gon constructible",
                 font_size=BODY_SIZE, color=WHITE, font=SANS),
            Text("if and only if phi(n) is a power of 2",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Gauss: 17-gon constructible (phi(17) = 16 = 2^4)",
                 font_size=BODY_SIZE, color=ACCENT, font=SANS),
            Text("Quadratic reciprocity: clean proof via cyclotomic fields",
                 font_size=BODY_SIZE, color=WHITE, font=SANS),
            Text("Fermat's Last Theorem: Kummer's ideal numbers",
                 font_size=BODY_SIZE, color=WHITE, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=title)
        self.wait(5)
        self.ly.clear()

    def scene7_connection_abel_ruffini(self):
        self.add_subcaption(
            "From Video 225, x to the 5th minus 1 is solvable by radicals. "
            "Now we see why. Its Galois group is cyclic of order 4, "
            "which is abelian and hence solvable. More generally, every "
            "cyclotomic polynomial is solvable by radicals.",
            duration=14,
        )
        title = self.ly.title("Connection to Abel-Ruffini")

        items = [
            MathTex(r"x^5 - 1: \text{Gal} = C_4 \text{ (abelian, solvable!)}",
                    font_size=HEADING_SIZE, color=SECONDARY),
            Text("Every cyclotomic polynomial is solvable by radicals",
                 font_size=BODY_SIZE, color=ACCENT, font=SANS),
            Text("Galois group (Z/nZ)* is always abelian",
                 font_size=BODY_SIZE, color=WHITE, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=title)
        self.wait(6)
        self.ly.clear()

    def scene8_summary(self):
        self.add_subcaption(
            "The n-th roots of unity sit on the unit circle. "
            "The cyclotomic polynomial Phi sub n has degree phi of n "
            "and is irreducible. The Galois group is Z mod n star. "
            "Applications include constructibility, reciprocity, and FLT. "
            "Next: finite fields.",
            duration=14,
        )
        self.ly.section_divider(5, "Summary")
        title = self.ly.title("Key Takeaways")

        items = [
            Text("n-th roots of unity: x^n = 1 on the unit circle",
                 font_size=BODY_SIZE, color=WHITE, font=SANS),
            Text("Cyclotomic polynomial: product over primitive roots, irreducible",
                 font_size=BODY_SIZE, color=WHITE, font=SANS),
            Text("[Q(zeta_n):Q] = phi(n)",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Gal(Q(zeta_n)/Q) isomorphic to (Z/nZ)*, action by exponentiation",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
            Text("Applications: constructibility, quadratic reciprocity, FLT",
                 font_size=BODY_SIZE, color=ACCENT, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=title)
        self.wait(4)
        self.ly.clear()

        play_outro(self, "Finite Fields", "Advanced Abstract Algebra")
