r"""
Video 218: Solvable and Nilpotent Groups — Advanced Abstract Algebra
Commutator subgroup, derived series, solvable groups, nilpotent groups,
upper and lower central series, hierarchy of group classes.

QUALITY RULES:
1. Max 5 visible elements per scene
2. LayoutEngine for ALL positioning
3. Progressive disclosure
4. Raw strings with single backslashes for LaTeX
5. ly.clear() between scenes
6. One subcaption per scene, self.wait(5-8) after content

Competitive analysis: Salomone (32K views, whiteboard, S3/S4 examples),
Borcherds (9.6K views, tablet, nilpotent = product of p-groups),
MathDoctorBob (30K views, whiteboard, commutator subgroup). All use
whiteboard — no Manim-animated video covers both solvable AND nilpotent
groups together. Our approach: animate the "peeling layers" metaphor,
color-code solvable vs nilpotent, visualize hierarchy of classes.
"""

from manim import *
import sys, os
_template_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "templates"))
if _template_dir not in sys.path:
    sys.path.insert(0, _template_dir)
from channel_branding import (
    BG, PRIMARY, SECONDARY, ACCENT, RED, DIM, WHITE, SANS, MONO,
    TITLE_SIZE, HEADING_SIZE, BODY_SIZE, LABEL_SIZE, FAST, NORMAL, SLOW,
    play_intro, play_outro, setup_background,
)
from layout import LayoutEngine, ensure_fits


class Video218_SolvableNilpotentGroups(Scene):
    """Solvable and Nilpotent Groups: measuring how close a group is to abelian."""

    def construct(self):
        self.camera.background_color = BG
        self.ly = LayoutEngine(self)
        self._bg_dots, self._bg_gradient = setup_background(self)

        self.scene1_hook()
        self.scene2_commutator()
        self.scene3_derived_series()
        self.scene4_solvable_definition()
        self.scene5_s3_solvable()
        self.scene6_s5_not_solvable()
        self.scene7_properties()
        self.scene8_central_series()
        self.scene9_nilpotent_definition()
        self.scene10_nilpotent_examples()
        self.scene11_comparison()
        self.scene12_summary()

    # ───────────────────────────────────────────────────────────────
    # Scene 1: Hook
    # ───────────────────────────────────────────────────────────────
    def scene1_hook(self):
        """Hook — why do we care about solvability?"""
        self.add_subcaption(
            "After studying group actions and the Sylow theorems, "
            "we now ask: which groups can be built from abelian pieces? "
            "This question leads us to solvable and nilpotent groups. "
            "The payoff is enormous: solvable groups tell us which "
            "polynomial equations have solutions by radicals.",
            duration=26,
        )
        play_intro(self, "Solvable and Nilpotent Groups", "Advanced Abstract Algebra")

        title = self.ly.title("How Close Is a Group to Being Abelian?")
        items = [
            Text("Commutator subgroup: measures non-abelianness",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Derived series: peel back layers of commutativity",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
            Text("Solvable groups: Galois groups of radical extensions",
                 font_size=BODY_SIZE, color=ACCENT, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=title)
        self.wait(8)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 2: The Commutator Subgroup
    # ───────────────────────────────────────────────────────────────
    def scene2_commutator(self):
        """Define the commutator and commutator subgroup."""
        self.add_subcaption(
            "Given a group G and two elements g and h, their commutator "
            "is defined as g h g inverse h inverse. This measures how "
            "much g and h fail to commute: if the commutator is the "
            "identity, then g and h commute. The commutator subgroup "
            "of G, denoted G prime, is generated by all commutators. "
            "It is always normal, and G over G prime is abelian.",
            duration=34,
        )
        self.ly.section_divider(1, "Commutator Subgroup")

        title = self.ly.title("The Commutator Subgroup")

        comm = MathTex(
            r"[g, h] = g h g^{-1} h^{-1}",
            font_size=HEADING_SIZE, color=PRIMARY,
        )
        self.ly.safe_place(comm, DOWN, anchor=title, buff=0.5)
        self.play(Write(comm), run_time=NORMAL)
        self.wait(3)

        note1 = Text(
            "[g,h] = e  iff  gh = hg  (g and h commute)",
            font_size=BODY_SIZE, color=SECONDARY, font=SANS,
        )
        self.ly.safe_place(note1, DOWN, anchor=comm, buff=0.4)
        self.play(FadeIn(note1, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(2)

        gprime = MathTex(
            r"G' = [G, G] = \langle [g,h] : g, h \in G \rangle",
            font_size=HEADING_SIZE, color=PRIMARY,
        )
        self.ly.safe_place(gprime, DOWN, anchor=note1, buff=0.5)
        self.play(Write(gprime), run_time=NORMAL)
        self.wait(2)

        props = Text(
            "G' is normal in G, and G/G' is abelian",
            font_size=BODY_SIZE, color=ACCENT, font=SANS,
        )
        self.ly.safe_place(props, DOWN, anchor=gprime, buff=0.4)
        self.play(FadeIn(props, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(6)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 3: Derived Series
    # ───────────────────────────────────────────────────────────────
    def scene3_derived_series(self):
        """Define the derived series by iterating the commutator subgroup."""
        self.add_subcaption(
            "To measure how far a group is from being abelian, we "
            "iterate the commutator subgroup. Define G superscript zero "
            "equals G, G superscript one equals G prime, G superscript two "
            "equals the commutator subgroup of G prime, and so on. "
            "This descending chain is called the derived series. "
            "If it eventually reaches the trivial group, the group is solvable.",
            duration=28,
        )
        self.ly.section_divider(2, "Derived Series")

        title = self.ly.title("The Derived Series")

        series = MathTex(
            r"G^{(0)} = G,\quad G^{(1)} = G',\quad G^{(2)} = (G')',\quad \cdots",
            font_size=BODY_SIZE, color=PRIMARY,
        )
        self.ly.safe_place(series, DOWN, anchor=title, buff=0.5)
        self.play(Write(series), run_time=NORMAL)
        self.wait(3)

        desc = Text(
            "Each step: commutator subgroup of the previous term",
            font_size=BODY_SIZE, color=SECONDARY, font=SANS,
        )
        self.ly.safe_place(desc, DOWN, anchor=series, buff=0.4)
        self.play(FadeIn(desc, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(2)

        chain = Text(
            "Normal chain: G > G' > G'' > ... > {e}",
            font_size=BODY_SIZE, color=ACCENT, font=SANS,
        )
        self.ly.safe_place(chain, DOWN, anchor=desc, buff=0.4)
        self.play(FadeIn(chain, shift=LEFT * 0.15), run_time=FAST)
        self.wait(6)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 4: Solvable Groups — Definition
    # ───────────────────────────────────────────────────────────────
    def scene4_solvable_definition(self):
        """Formal definition of solvable group."""
        self.add_subcaption(
            "A group G is solvable if its derived series terminates "
            "at the trivial group after finitely many steps. Equivalently, "
            "there exists a chain of subgroups from G down to the identity "
            "where each is normal in the previous one and each quotient "
            "is abelian. The term solvable comes from Galois theory: "
            "a polynomial is solvable by radicals if and only if its "
            "Galois group is solvable.",
            duration=30,
        )
        self.ly.section_divider(3, "Solvable Groups")

        title = self.ly.title("Definition: Solvable Group")

        defn = MathTex(
            r"G^{(n)} = \{e\} \text{ for some } n \geq 0",
            font_size=HEADING_SIZE, color=PRIMARY,
        )
        boxed = self.ly.formula_box(defn, color=PRIMARY)
        self.ly.safe_place(boxed, DOWN, anchor=title, buff=0.5)
        self.play(FadeIn(boxed), run_time=NORMAL)
        self.wait(3)

        note = Text(
            "Each quotient G^(k) / G^(k+1) is abelian",
            font_size=BODY_SIZE, color=SECONDARY, font=SANS,
        )
        self.ly.safe_place(note, DOWN, anchor=boxed, buff=0.5)
        self.play(FadeIn(note, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(2)

        galois = Text(
            "Galois: polynomial solvable by radicals "
            "iff Galois group is solvable",
            font_size=BODY_SIZE, color=ACCENT, font=SANS,
        )
        self.ly.safe_place(galois, DOWN, anchor=note, buff=0.4)
        self.play(FadeIn(galois, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(6)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 5: S_3 is solvable
    # ───────────────────────────────────────────────────────────────
    def scene5_s3_solvable(self):
        """Worked example: S_3 is solvable."""
        self.add_subcaption(
            "Let us verify that S 3 is solvable. The commutator subgroup "
            "of S 3 is the alternating group A 3, which is cyclic of "
            "order 3 and therefore abelian. The commutator subgroup of "
            "A 3 is trivial. So the derived series is S 3, then A 3, "
            "then the trivial group, reaching the identity in two steps. "
            "The quotients are Z mod 2 and Z mod 3, both abelian.",
            duration=28,
        )
        title = self.ly.title("Example: S_3 is Solvable")

        series = MathTex(
            r"S_3 \triangleright A_3 \triangleright \{e\}",
            font_size=HEADING_SIZE, color=PRIMARY,
        )
        boxed = self.ly.formula_box(series, color=PRIMARY)
        self.ly.safe_place(boxed, DOWN, anchor=title, buff=0.5)
        self.play(FadeIn(boxed), run_time=NORMAL)
        self.wait(3)

        items = [
            MathTex(r"S_3 / A_3 \cong \mathbb{Z}/2\mathbb{Z}\text{ (abelian)}",
                    font_size=BODY_SIZE, color=SECONDARY),
            MathTex(r"A_3 / \{e\} \cong \mathbb{Z}/3\mathbb{Z}\text{ (abelian)}",
                    font_size=BODY_SIZE, color=SECONDARY),
            Text("Derived series reaches {e} in 2 steps: solvable!",
                 font_size=BODY_SIZE, color=ACCENT, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=boxed)
        self.wait(6)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 6: S_5 is NOT solvable
    # ───────────────────────────────────────────────────────────────
    def scene6_s5_not_solvable(self):
        """S_5 is not solvable — the key example."""
        self.add_subcaption(
            "In stark contrast, S 5 is not solvable. Its commutator "
            "subgroup is A 5, and A 5 is simple, meaning it has no "
            "nontrivial normal subgroups. The commutator subgroup of "
            "A 5 is A 5 itself. So the derived series of S 5 never "
            "reaches the trivial group. This is why the general "
            "quintic equation cannot be solved by radicals.",
            duration=28,
        )
        self.ly.section_divider(4, "A Non-Solvable Example")

        title = self.ly.title("S_5 is NOT Solvable")

        series = MathTex(
            r"S_5 \triangleright A_5 = A_5 = A_5 = \cdots",
            font_size=HEADING_SIZE, color=RED,
        )
        boxed = self.ly.formula_box(series, color=RED)
        self.ly.safe_place(boxed, DOWN, anchor=title, buff=0.5)
        self.play(FadeIn(boxed), run_time=NORMAL)
        self.wait(3)

        items = [
            Text("A_5 is simple: A_5' = A_5 (series stabilizes)",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
            Text("Derived series never reaches {e}",
                 font_size=BODY_SIZE, color=RED, font=SANS),
            Text("Consequence: the general quintic has no radical formula",
                 font_size=BODY_SIZE, color=ACCENT, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=boxed)
        self.wait(6)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 7: Key Properties of Solvable Groups
    # ───────────────────────────────────────────────────────────────
    def scene7_properties(self):
        """Subgroups and quotients of solvable groups are solvable."""
        self.add_subcaption(
            "Solvable groups have excellent closure properties. Every "
            "subgroup of a solvable group is solvable. Every quotient of "
            "a solvable group is solvable. If N is a normal subgroup of "
            "G and both N and G over N are solvable, then G itself is "
            "solvable. Also, every finite p-group is solvable, and all "
            "abelian groups are trivially solvable since G prime is trivial.",
            duration=30,
        )
        self.ly.section_divider(5, "Properties of Solvable Groups")

        title = self.ly.title("Closure Properties")

        items = [
            Text("Subgroups of solvable groups are solvable",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Quotients of solvable groups are solvable",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("If N normal in G, N and G/N solvable => G solvable",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
            Text("Every abelian group is solvable: G prime is trivial",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=title)
        self.wait(7)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 8: Upper and Lower Central Series
    # ───────────────────────────────────────────────────────────────
    def scene8_central_series(self):
        """Define the upper and lower central series."""
        self.add_subcaption(
            "Nilpotent groups use a different measuring stick: the central "
            "series. The upper central series starts at the identity and "
            "builds upward. Z zero is trivial, Z one is the center of G, "
            "Z two is the preimage of the center of G over Z one, and so on. "
            "The lower central series starts at G and descends: gamma one "
            "equals G, gamma two equals the commutator subgroup of G, "
            "and each step is the commutator with G.",
            duration=34,
        )
        self.ly.section_divider(6, "Central Series")

        title = self.ly.title("Upper Central Series")

        upper = MathTex(
            r"Z_0 = \{e\},\quad Z_1 = Z(G),\quad Z_{i+1}/Z_i = Z(G/Z_i)",
            font_size=BODY_SIZE, color=PRIMARY,
        )
        self.ly.safe_place(upper, DOWN, anchor=title, buff=0.5)
        self.play(Write(upper), run_time=NORMAL)
        self.wait(3)

        note_upper = Text(
            "Builds upward from the center",
            font_size=BODY_SIZE, color=SECONDARY, font=SANS,
        )
        self.ly.safe_place(note_upper, DOWN, anchor=upper, buff=0.4)
        self.play(FadeIn(note_upper, shift=LEFT * 0.15), run_time=FAST)
        self.wait(4)
        self.ly.clear()

        # Lower central series in same scene for continuity
        self.add_subcaption(
            "The lower central series goes in the opposite direction. "
            "Gamma one is G itself. Gamma two is the commutator "
            "subgroup G prime. In general, gamma k plus one is the "
            "commutator subgroup of gamma k with G. A group is nilpotent "
            "if either central series reaches the other end.",
            duration=26,
        )
        title2 = self.ly.title("Lower Central Series")

        lower = MathTex(
            r"\gamma_1 = G,\quad \gamma_2 = G',\quad "
            r"\gamma_{i+1} = [\gamma_i, G]",
            font_size=BODY_SIZE, color=PRIMARY,
        )
        self.ly.safe_place(lower, DOWN, anchor=title2, buff=0.5)
        self.play(Write(lower), run_time=NORMAL)
        self.wait(3)

        note_lower = Text(
            "Descends via commutators with G",
            font_size=BODY_SIZE, color=SECONDARY, font=SANS,
        )
        self.ly.safe_place(note_lower, DOWN, anchor=lower, buff=0.4)
        self.play(FadeIn(note_lower, shift=LEFT * 0.15), run_time=FAST)
        self.wait(5)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 9: Nilpotent Groups — Definition
    # ───────────────────────────────────────────────────────────────
    def scene9_nilpotent_definition(self):
        """Formal definition and equivalent characterizations."""
        self.add_subcaption(
            "A group G is nilpotent if its lower central series "
            "reaches the trivial group. Equivalently, the upper central "
            "series reaches G itself. For finite groups, nilpotent is "
            "equivalent to being a direct product of Sylow p-subgroups. "
            "Every nilpotent group is solvable, but not conversely. "
            "Abelian groups are the simplest nilpotent groups of class one.",
            duration=30,
        )
        self.ly.section_divider(7, "Nilpotent Groups")

        title = self.ly.title("Definition: Nilpotent Group")

        defn = MathTex(
            r"\gamma_{c+1} = \{e\} \text{ for some } c \geq 0",
            font_size=HEADING_SIZE, color=SECONDARY,
        )
        boxed = self.ly.formula_box(defn, color=SECONDARY)
        self.ly.safe_place(boxed, DOWN, anchor=title, buff=0.5)
        self.play(FadeIn(boxed), run_time=NORMAL)
        self.wait(3)

        equiv = Text(
            "Equivalent: upper central series Z_c = G",
            font_size=BODY_SIZE, color=PRIMARY, font=SANS,
        )
        self.ly.safe_place(equiv, DOWN, anchor=boxed, buff=0.5)
        self.play(FadeIn(equiv, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(2)

        finite_char = Text(
            "Finite: nilpotent iff direct product of Sylow p-subgroups",
            font_size=BODY_SIZE, color=ACCENT, font=SANS,
        )
        self.ly.safe_place(finite_char, DOWN, anchor=equiv, buff=0.4)
        self.play(FadeIn(finite_char, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(7)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 10: Nilpotent Examples
    # ───────────────────────────────────────────────────────────────
    def scene10_nilpotent_examples(self):
        """Q_8 and D_8 as nilpotent groups."""
        self.add_subcaption(
            "The quaternion group Q 8 has center Z Q 8 equal to "
            "plus minus 1, which has order 2. The upper central series "
            "is trivial, then the center, then Q 8 itself. So Q 8 is "
            "nilpotent of class 2. Similarly, the dihedral group D 8 is "
            "nilpotent of class 2, since its center has order 2. In "
            "fact, all groups of order p to the n are nilpotent.",
            duration=30,
        )
        self.ly.section_divider(8, "Nilpotent Examples")

        title = self.ly.title("The Quaternion Group Q_8")

        q8_series = MathTex(
            r"\{e\} \subset Z(Q_8) = \{\pm 1\} \subset Q_8",
            font_size=HEADING_SIZE, color=SECONDARY,
        )
        boxed = self.ly.formula_box(q8_series, color=SECONDARY)
        self.ly.safe_place(boxed, DOWN, anchor=title, buff=0.5)
        self.play(FadeIn(boxed), run_time=NORMAL)
        self.wait(3)

        items = [
            Text("Upper central series: {e} -> Z(Q_8) -> Q_8",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Nilpotent of class 2",
                 font_size=BODY_SIZE, color=ACCENT, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=boxed)
        self.wait(4)

        # D_8 example
        self.play(FadeOut(boxed), FadeOut(items[0]), FadeOut(items[1]),
                  run_time=FAST)
        d8_title = Text("D_8 (dihedral group of order 8):",
                         font_size=BODY_SIZE, color=PRIMARY, font=SANS)
        self.ly.safe_place(d8_title, DOWN, anchor=title, buff=0.5)
        self.play(FadeIn(d8_title, shift=LEFT * 0.15), run_time=FAST)

        d8_note = Text(
            "Also nilpotent of class 2 (center has order 2)",
            font_size=BODY_SIZE, color=SECONDARY, font=SANS,
        )
        self.ly.safe_place(d8_note, DOWN, anchor=d8_title, buff=0.4)
        self.play(FadeIn(d8_note, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(6)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 11: Solvable vs Nilpotent Comparison
    # ───────────────────────────────────────────────────────────────
    def scene11_comparison(self):
        """Compare the two classes and show the hierarchy."""
        self.add_subcaption(
            "How do solvable and nilpotent groups compare? Every nilpotent "
            "group is solvable, but the converse fails. For example, S 3 "
            "is solvable but not nilpotent, because its center is trivial. "
            "The full hierarchy is: cyclic groups are contained in abelian "
            "groups, which are contained in nilpotent groups, which are "
            "contained in solvable groups, which are contained in all groups.",
            duration=32,
        )
        self.ly.section_divider(9, "Solvable vs Nilpotent")

        title = self.ly.title("How Do They Compare?")

        # Hierarchy: cyclic < abelian < nilpotent < solvable
        hierarchy = MathTex(
            r"\text{cyclic} \subset \text{abelian} "
            r"\subset \text{nilpotent} \subset \text{solvable}",
            font_size=BODY_SIZE, color=PRIMARY,
        )
        boxed = self.ly.formula_box(hierarchy, color=PRIMARY)
        self.ly.safe_place(boxed, DOWN, anchor=title, buff=0.5)
        self.play(FadeIn(boxed), run_time=NORMAL)
        self.wait(3)

        # Counterexample
        counter_title = Text(
            "Solvable but NOT nilpotent:",
            font_size=BODY_SIZE, color=RED, font=SANS,
        )
        self.ly.safe_place(counter_title, DOWN, anchor=boxed, buff=0.5)
        self.play(FadeIn(counter_title, shift=LEFT * 0.15), run_time=FAST)

        counter_ex = Text(
            "S_3: solvable (derived series: S_3 > A_3 > {e}) "
            "but Z(S_3) = {e}, so not nilpotent",
            font_size=LABEL_SIZE, color=RED, font=SANS,
        )
        self.ly.safe_place(counter_ex, DOWN, anchor=counter_title, buff=0.3)
        self.play(FadeIn(counter_ex, shift=LEFT * 0.15), run_time=NORMAL)
        self.wait(7)
        self.ly.clear()

    # ───────────────────────────────────────────────────────────────
    # Scene 12: Summary and Outro
    # ───────────────────────────────────────────────────────────────
    def scene12_summary(self):
        """Summary of key concepts and outro."""
        self.add_subcaption(
            "Let us summarize. The commutator subgroup measures how far "
            "a group is from being abelian. Iterating it gives the derived "
            "series, and if this terminates, the group is solvable. Solvable "
            "groups are precisely the Galois groups of solvable-by-radicals "
            "polynomials. Nilpotent groups use the central series instead and "
            "are a strictly smaller class. They are equivalent to direct "
            "products of p-groups when finite. In the next video we begin "
            "our study of field extensions, the gateway to Galois theory.",
            duration=34,
        )
        self.ly.section_divider(10, "Summary")

        title = self.ly.title("Key Takeaways")

        items = [
            Text("[g,h] = ghg^{-1}h^{-1}: measures non-commutativity",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Derived series: iterate commutator subgroup",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
            Text("Solvable: derived series reaches {e}",
                 font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("Nilpotent: central series connects {e} to G",
                 font_size=BODY_SIZE, color=SECONDARY, font=SANS),
        ]
        self.ly.progressive_reveal(items, start_from=title)
        self.wait(3)

        # Final takeaway (replaces oldest)
        extra = Text(
            "Hierarchy: cyclic < abelian < nilpotent < solvable",
            font_size=BODY_SIZE, color=ACCENT, font=SANS,
        )
        self.ly.progressive_reveal([extra], start_from=items[-1])
        self.wait(5)
        self.ly.clear()

        self.add_subcaption(
            "Thank you for watching! In the next video we will "
            "study field extensions.",
            duration=10,
        )
        play_outro(self, "Field Extensions", "Advanced Abstract Algebra")