"""Video 112: Subgroups and Cyclic Groups
TEMPLATE v2 -- Professional quality Manim script

Playlist: Abstract Algebra I (Video 2 of 12)
Class: Video112_SubgroupsAndCyclicGroups
"""

from manim import *
import numpy as np
import sys, os
_template_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "templates"))
if _template_dir not in sys.path:
    sys.path.insert(0, _template_dir)
from channel_branding import (
    BG, PRIMARY, SECONDARY, ACCENT, RED, DIM, WHITE, SANS, MONO,
    TITLE_SIZE, HEADING_SIZE, BODY_SIZE, LABEL_SIZE, SMALL_SIZE, FAST, NORMAL, SLOW,
    play_intro, play_outro, setup_background,
)
from layout import LayoutEngine, ensure_fits, clamp_position


class Video112_SubgroupsAndCyclicGroups(Scene):

    def construct(self):
        self.camera.background_color = BG
        self.ly = LayoutEngine(self)
        self._bg_dots, self._bg_gradient = setup_background(self)

        self.scene1_hook()
        self.scene2_subgroup_def()
        self.scene3_examples()
        self.scene4_subgroup_test()
        self.scene5_cyclic_def()
        self.scene6_generators_visual()
        self.scene7_z12_lattice()
        self.scene8_properties()
        self.scene9_summary()

    # --- Scene 1: Hook ---

    def scene1_hook(self):
        self.add_subcaption(
            "Last time we defined what a group is. "
            "Now we look inside a group for smaller groups hiding inside. "
            "These are called subgroups. "
            "And some groups can be generated by just one element spinning around. "
            "These are cyclic groups. "
            "Today we will see how subgroups and cyclic groups work "
            "and why they are so fundamental to abstract algebra.",
            duration=19.9,
        )
        play_intro(self, "Subgroups and Cyclic Groups", "Abstract Algebra I")

        title = self.ly.title("Groups Within Groups")

        g_label = Text(
            "G = {0, 1, 2, 3, 4, 5}",
            font_size=BODY_SIZE, color=WHITE, font=MONO,
        )
        self.ly.safe_place(g_label, anchor=title, direction=DOWN, buff=0.6)
        self.play(Write(g_label), run_time=NORMAL)
        self.wait(0.2)

        sub = Text(
            "H = {0, 2, 4}",
            font_size=HEADING_SIZE, color=PRIMARY, font=MONO,
        )
        self.ly.safe_place(sub, anchor=g_label, direction=DOWN, buff=0.5)
        self.play(Write(sub), run_time=NORMAL)
        self.wait(0.2)

        arrow = MathTex(
            r"\{0,\,2,\,4\} \subseteq \{0,\,1,\,2,\,3,\,4,\,5\}",
            color=SECONDARY, font_size=30,
        )
        self.ly.safe_place(arrow, anchor=sub, direction=DOWN, buff=0.5)
        self.play(Write(arrow), run_time=NORMAL)
        self.wait(0.2)

        note = Text(
            "H is itself a group under the same operation!",
            font_size=BODY_SIZE, color=ACCENT, font=SANS,
        )
        self.ly.safe_place(note, anchor=arrow, direction=DOWN, buff=0.4)
        self.play(FadeIn(note, shift=LEFT * 0.15), run_time=FAST)
        # pacing: extends previous caption slot (seg#0 natural 19.9s, slot 16.07s -> 24.97s, Δ=8.9)
        self.wait(9.4)

        self.ly.clear()

    # --- Scene 2: Subgroup Definition ---

    def scene2_subgroup_def(self):
        self.ly.section_divider(1, "Subgroups")

        self.add_subcaption(
            "The formal definition is clean. "
            "A subset H of a group G is a subgroup "
            "if H is itself a group using the same operation. "
            "We write H is less than or equal to G. "
            "There are two trivial examples: "
            "the whole group G itself is always a subgroup of G, "
            "and the set containing just the identity element is always a subgroup. "
            "These are called the improper and trivial subgroups.",
            duration=25.7,
        )

        title = self.ly.title("Definition: Subgroup")

        defn = Text(
            "A subset H of a group G is a subgroup if",
            font_size=HEADING_SIZE, color=WHITE, font=SANS,
        )
        self.ly.safe_place(defn, anchor=title, direction=DOWN, buff=0.5)
        self.play(Write(defn), run_time=NORMAL)
        self.wait(0.2)

        defn2 = Text(
            "H is itself a group under the same operation.",
            font_size=HEADING_SIZE, color=WHITE, font=SANS,
        )
        self.ly.safe_place(defn2, anchor=defn, direction=DOWN, buff=0.3)
        self.play(Write(defn2), run_time=NORMAL)
        self.wait(0.2)

        notation = MathTex(
            r"H \leq G",
            color=ACCENT, font_size=40,
        )
        self.ly.safe_place(notation, anchor=defn2, direction=DOWN, buff=0.5)
        self.play(Write(notation), run_time=NORMAL)
        self.wait(0.2)

        trivial = Text(
            "Trivial: {e} (identity alone)",
            font_size=BODY_SIZE, color=DIM, font=SANS,
        )
        self.ly.safe_place(trivial, anchor=notation, direction=DOWN, buff=0.4)
        self.play(FadeIn(trivial, shift=LEFT * 0.15), run_time=FAST)
        self.wait(0.2)

        improper = Text(
            "Improper: G itself (the whole group)",
            font_size=BODY_SIZE, color=DIM, font=SANS,
        )
        self.ly.safe_place(improper, anchor=trivial, direction=DOWN, buff=0.35)
        self.play(FadeIn(improper, shift=LEFT * 0.15), run_time=FAST)
        # pacing: extends previous caption slot (seg#1 natural 25.7s, slot 7.63s -> 32.13s, Δ=24.5)
        self.wait(25.0)

        self.ly.clear()

    # --- Scene 3: Subgroup Examples ---

    def scene3_examples(self):
        self.add_subcaption(
            "Let us look at concrete examples. "
            "The even integers 2Z are a subgroup of the integers Z under addition. "
            "If you add two even numbers, you get an even number. "
            "Zero is the identity, and every even number has an even negative. "
            "In our clock example, the set {0, 3} is a subgroup of Z6. "
            "Zero plus three is three, "
            "three plus three wraps to zero. "
            "It satisfies all the group axioms with just two elements. "
            "In the dihedral group D3, the rotations alone form a subgroup. "
            "The three rotations close under composition, "
            "while the reflections do not.",
            duration=40.0,
        )

        title = self.ly.title("Examples of Subgroups")

        ex1_title = MathTex(
            r"2\mathbb{Z} = \{\ldots, -4, -2, 0, 2, 4, \ldots\} \leq \mathbb{Z}",
            color=PRIMARY, font_size=28,
        )
        self.ly.safe_place(ex1_title, anchor=title, direction=DOWN, buff=0.5)
        self.play(Write(ex1_title), run_time=NORMAL)
        self.wait(0.2)

        ex1_check = Text(
            "Even + even = even  (closed)",
            font_size=BODY_SIZE, color=SECONDARY, font=SANS,
        )
        self.ly.safe_place(ex1_check, anchor=ex1_title, direction=DOWN, buff=0.35)
        self.play(FadeIn(ex1_check, shift=LEFT * 0.15), run_time=FAST)
        # pacing: extends previous caption slot (seg#2 natural 40.0s, slot 9.27s -> 50.17s, Δ=40.9)
        self.wait(41.2)

        self.ly.clear()

        title2 = self.ly.title("Examples: Z6")

        ex2_set = MathTex(
            r"H = \{0,\, 3\} \leq \mathbb{Z}_6",
            color=PRIMARY, font_size=30,
        )
        self.ly.safe_place(ex2_set, anchor=title2, direction=DOWN, buff=0.5)
        self.play(Write(ex2_set), run_time=NORMAL)
        self.wait(0.2)

        ex2_table = VGroup(
            MathTex(r"0 + 3 = 3", color=WHITE, font_size=26),
            MathTex(r"3 + 3 \equiv 0 \pmod{6}", color=WHITE, font_size=26),
            MathTex(r"\text{Identity: } 0", color=SECONDARY, font_size=26),
            MathTex(r"\text{Inverse: } 0^{-1}=0,\; 3^{-1}=3", color=SECONDARY, font_size=26),
        ).arrange(DOWN, buff=0.3, aligned_edge=LEFT)
        self.ly.safe_place(ex2_table, anchor=ex2_set, direction=DOWN, buff=0.4)
        self.play(Write(ex2_table), run_time=NORMAL)
        self.wait(0.2)

        result = Text(
            "All axioms satisfied!",
            font_size=HEADING_SIZE, color=SECONDARY, font=SANS, weight=BOLD,
        )
        self.ly.safe_place(result, anchor=ex2_table, direction=DOWN, buff=0.4)
        self.play(FadeIn(result, scale=1.05), run_time=FAST)
        self.wait(0.5)

        self.ly.clear()

    # --- Scene 4: Subgroup Test ---

    def scene4_subgroup_test(self):
        self.add_subcaption(
            "Checking all four group axioms for a subset is tedious. "
            "The subgroup test simplifies this to one condition. "
            "If H is a non-empty subset of G, "
            "then H is a subgroup if and only if "
            "for all a and b in H, "
            "a times b-inverse is in H. "
            "This one condition guarantees closure, identity, and inverses all at once. "
            "The proof works by showing that "
            "since H is non-empty, pick any element a. "
            "Then a times a-inverse equals the identity, "
            "so the identity is in H. "
            "Then the inverse of a is in H by the same condition. "
            "And closure follows by a similar argument.",
            duration=40.2,
        )

        title = self.ly.title("The Subgroup Test")

        defn = Text(
            "H != {} and H <= G  iff:",
            font_size=HEADING_SIZE, color=WHITE, font=SANS,
        )
        self.ly.safe_place(defn, anchor=title, direction=DOWN, buff=0.5)
        self.play(Write(defn), run_time=NORMAL)
        self.wait(0.2)

        condition = MathTex(
            r"\forall\, a, b \in H:\quad a \cdot b^{-1} \in H",
            color=ACCENT, font_size=34,
        )
        self.ly.safe_place(condition, anchor=defn, direction=DOWN, buff=0.5)
        self.play(Write(condition), run_time=NORMAL)
        self.wait(0.3)

        boxed = SurroundingRectangle(condition, color=ACCENT, buff=0.2, stroke_width=2)
        self.play(Create(boxed), run_time=FAST)
        self.wait(0.2)

        insight = Text(
            "One condition replaces checking all four axioms!",
            font_size=BODY_SIZE, color=PRIMARY, font=SANS,
        )
        self.ly.safe_place(insight, anchor=condition, direction=DOWN, buff=0.5)
        self.play(FadeIn(insight, shift=LEFT * 0.15), run_time=FAST)
        # pacing: extends previous caption slot (seg#3 natural 40.2s, slot 16.73s -> 50.33s, Δ=33.6)
        self.wait(33.9)

        self.ly.clear()

        # Quick proof sketch
        title2 = self.ly.title("Proof Sketch")

        steps = [
            MathTex(r"1.\; \text{Pick } a \in H\; (\text{H is non-empty})", color=PRIMARY, font_size=28),
            MathTex(r"2.\; a \cdot a^{-1} = e \implies e \in H", color=SECONDARY, font_size=28),
            MathTex(r"3.\; e \cdot a^{-1} = a^{-1} \implies a^{-1} \in H", color=ACCENT, font_size=28),
            MathTex(r"4.\; \text{Closure follows from } a \cdot (b^{-1})^{-1} = a \cdot b", color=WHITE, font_size=28),
        ]

        prev = title2
        for step in steps:
            self.ly.safe_place(step, anchor=prev, direction=DOWN, buff=0.4)
            self.play(Write(step), run_time=NORMAL)
            self.wait(0.2)
            prev = step

        self.wait(0.5)
        self.ly.clear()

    # --- Scene 5: Cyclic Groups Definition ---

    def scene5_cyclic_def(self):
        self.ly.section_divider(2, "Cyclic Groups")

        self.add_subcaption(
            "Now for cyclic groups. "
            "A group G is cyclic if there exists an element g "
            "such that every element of G is a power of g. "
            "We call g a generator, and write G equals the angle brackets g. "
            "The simplest cyclic group is Z6, "
            "which is generated by the element 1. "
            "Starting from zero, keep adding 1: 1, 2, 3, 4, 5, and back to 0. "
            "Every element appears. "
            "Under addition, this means repeated addition. "
            "Under multiplication, it means repeated multiplication. "
            "Every cyclic group is abelian, "
            "because powers of the same element always commute.",
            duration=40.6,
        )

        title = self.ly.title("Definition: Cyclic Group")

        defn = Text(
            "G is cyclic if some element g generates all of G:",
            font_size=HEADING_SIZE, color=WHITE, font=SANS,
        )
        self.ly.safe_place(defn, anchor=title, direction=DOWN, buff=0.5)
        self.play(Write(defn), run_time=NORMAL)
        self.wait(0.2)

        formula = MathTex(
            r"G = \langle g \rangle = \{e,\, g,\, g^2,\, g^3,\, \ldots\}",
            color=ACCENT, font_size=32,
        )
        self.ly.safe_place(formula, anchor=defn, direction=DOWN, buff=0.5)
        self.play(Write(formula), run_time=NORMAL)
        self.wait(0.3)

        boxed = SurroundingRectangle(formula, color=ACCENT, buff=0.2, stroke_width=2)
        self.play(Create(boxed), run_time=FAST)
        self.wait(0.2)

        gen_label = Text(
            "g is called a GENERATOR of G",
            font_size=BODY_SIZE, color=PRIMARY, font=SANS,
        )
        self.ly.safe_place(gen_label, anchor=formula, direction=DOWN, buff=0.5)
        self.play(FadeIn(gen_label, shift=LEFT * 0.15), run_time=FAST)
        self.wait(0.2)

        abelian_note = MathTex(
            r"\text{Every cyclic group is abelian: } g^a \cdot g^b = g^{a+b} = g^{b+a}",
            color=SECONDARY, font_size=26,
        )
        self.ly.safe_place(abelian_note, anchor=gen_label, direction=DOWN, buff=0.4)
        self.play(Write(abelian_note), run_time=NORMAL)
        # pacing: extends previous caption slot (seg#4 natural 40.6s, slot 7.70s -> 50.80s, Δ=43.1)
        self.wait(43.6)

        self.ly.clear()

    # --- Scene 6: Visualizing Generators ---

    def scene6_generators_visual(self):
        self.add_subcaption(
            "Let us visualize how a single generator can produce an entire group. "
            "Take Z12 under addition. "
            "Starting from 0, repeatedly add 1: "
            "1, 2, 3, up to 11, and back to 0. "
            "The element 1 generates the whole group. "
            "But 1 is not the only generator. "
            "The element 5 also generates Z12, "
            "since the multiples of 5 modulo 12 give: "
            "5, 10, 3, 8, 1, 6, 11, 4, 9, 2, 7, 0. "
            "Every element appears! "
            "An element generates Zn if and only if "
            "it is coprime to n.",
            duration=41.7,
        )

        title = self.ly.title("Visualizing a Generator: Z12")

        # Clock with 12 positions
        circle_r = 1.8
        clock = Circle(radius=circle_r, color=PRIMARY, stroke_width=2)
        clock_nums = VGroup()
        for i in range(12):
            angle = PI / 2 - i * TAU / 12
            pos = np.array([
                np.cos(angle),
                np.sin(angle),
                0,
            ]) * (circle_r * 0.82)
            num = Text(str(i), font_size=LABEL_SIZE, color=DIM, font=MONO)
            num.move_to(pos)
            clock_nums.add(num)
        clock_group = VGroup(clock, clock_nums)

        self.ly.center_in_content(clock_group)
        self.play(Create(clock_group), run_time=NORMAL)
        self.wait(0.2)

        # Highlight generator 1 path with dots
        gen_label = Text(
            "Generator: 1  (add 1 each step)",
            font_size=BODY_SIZE, color=ACCENT, font=SANS,
        )
        self.ly.safe_place(gen_label, anchor=clock, direction=DOWN, buff=0.5)
        self.play(FadeIn(gen_label, shift=LEFT * 0.15), run_time=FAST)
        self.wait(0.3)

        # Animate stepping through 1, 2, 3... by highlighting dots
        highlight_dots = []
        for i in range(1, 12):
            angle = PI / 2 - i * TAU / 12
            pos = np.array([
                np.cos(angle),
                np.sin(angle),
                0,
            ]) * (circle_r * 0.82)
            dot = Dot(pos, color=SECONDARY, radius=0.08)
            highlight_dots.append(dot)

        # Show dots in batches of 3
        for batch_start in range(0, 12, 3):
            batch = highlight_dots[batch_start:batch_start + 3]
            if batch:
                self.play(*[FadeIn(d) for d in batch], run_time=FAST)
                self.wait(0.15)

        self.wait(0.2)

        # Now show 5 as another generator
        gen_label2 = Text(
            "Also a generator: 5 (coprime to 12)",
            font_size=BODY_SIZE, color=ACCENT, font=SANS,
        )
        self.ly.safe_place(gen_label2, anchor=gen_label, direction=DOWN, buff=0.35)
        self.play(FadeIn(gen_label2, shift=LEFT * 0.15), run_time=FAST)
        self.wait(0.2)

        # Clean up and show 5 path
        self.play(*[FadeOut(d) for d in highlight_dots], run_time=0.3)
        self.wait(0.1)

        five_steps = [5, 10, 3, 8, 1, 6, 11, 4, 9, 2, 7, 0]
        five_dots = []
        for val in five_steps:
            angle = PI / 2 - val * TAU / 12
            pos = np.array([
                np.cos(angle),
                np.sin(angle),
                0,
            ]) * (circle_r * 0.82)
            dot = Dot(pos, color=RED, radius=0.08)
            five_dots.append(dot)

        for batch_start in range(0, 12, 4):
            batch = five_dots[batch_start:batch_start + 4]
            if batch:
                self.play(*[FadeIn(d) for d in batch], run_time=FAST)
                self.wait(0.15)

        # pacing: extends previous caption slot (seg#5 natural 41.7s, slot 10.63s -> 52.23s, Δ=41.6)
        self.wait(41.9)

        self.ly.clear()

    # --- Scene 7: Subgroup Lattice of Z12 ---

    def scene7_z12_lattice(self):
        self.add_subcaption(
            "Here is one of the most beautiful facts about cyclic groups. "
            "Every subgroup of a cyclic group is itself cyclic. "
            "And the subgroups of Z12 correspond to the divisors of 12. "
            "The divisors are 1, 2, 3, 4, 6, and 12. "
            "So Z12 has exactly these six subgroups. "
            "Each subgroup is generated by 12 over d. "
            "For example, 12 over 3 equals 4, "
            "so 4 generates a subgroup of order 3: {0, 4, 8}. "
            "This lattice structure is perfect and predictable.",
            duration=35.5,
        )

        title = self.ly.title("Subgroups of Z12")

        theorem = Text(
            "Every subgroup of a cyclic group is cyclic!",
            font_size=HEADING_SIZE, color=ACCENT, font=SANS, weight=BOLD,
        )
        self.ly.safe_place(theorem, anchor=title, direction=DOWN, buff=0.5)
        self.play(FadeIn(theorem, scale=1.05), run_time=NORMAL)
        self.wait(0.3)

        # Divisors of 12
        divisors = MathTex(
            r"\text{Divisors of } 12: \;\; 1,\; 2,\; 3,\; 4,\; 6,\; 12",
            color=PRIMARY, font_size=28,
        )
        self.ly.safe_place(divisors, anchor=theorem, direction=DOWN, buff=0.5)
        self.play(Write(divisors), run_time=NORMAL)
        self.wait(0.2)

        # Lattice diagram - show subgroups with their orders
        sub_data = [
            ("{0}", 1, UP * 2.0),
            ("{0, 6}", 2, UP * 1.0 + LEFT * 1.5),
            ("{0, 4, 8}", 3, UP * 1.0 + RIGHT * 1.5),
            ("{0, 3, 6, 9}", 4, DOWN * 0.3 + LEFT * 2.2),
            ("{0, 2, 4, 6, 8, 10}", 6, DOWN * 0.3 + RIGHT * 0.0),
            ("Z12", 12, DOWN * 1.4 + RIGHT * 0.0),
        ]

        sub_labels = VGroup()
        sub_mobjects = []
        for label_text, order, position in sub_data:
            lbl = MathTex(label_text, color=SECONDARY, font_size=22)
            lbl.move_to(position)
            sub_labels.add(lbl)
            sub_mobjects.append(lbl)

        self.ly.safe_place(sub_labels, anchor=divisors, direction=DOWN, buff=0.5)
        self.play(Write(sub_labels), run_time=NORMAL)
        self.wait(0.2)

        # Add edges between connected subgroups
        edges = VGroup()
        edge_pairs = [
            (sub_mobjects[0], sub_mobjects[1]),  # {0} -> {0,6}
            (sub_mobjects[0], sub_mobjects[2]),  # {0} -> {0,4,8}
            (sub_mobjects[1], sub_mobjects[3]),  # {0,6} -> {0,3,6,9}
            (sub_mobjects[1], sub_mobjects[4]),  # {0,6} -> {0,2,4,6,8,10}
            (sub_mobjects[2], sub_mobjects[3]),  # {0,4,8} -> {0,3,6,9}
            (sub_mobjects[2], sub_mobjects[4]),  # {0,4,8} -> {0,2,4,6,8,10}
            (sub_mobjects[3], sub_mobjects[5]),  # {0,3,6,9} -> Z12
            (sub_mobjects[4], sub_mobjects[5]),  # {0,2,4,6,8,10} -> Z12
        ]
        for a, b in edge_pairs:
            line = Line(a.get_center(), b.get_center(), color=DIM, stroke_width=1.5)
            edges.add(line)
        self.play(Create(edges), run_time=NORMAL)
        # pacing: extends previous caption slot (seg#6 natural 35.5s, slot 7.50s -> 44.40s, Δ=36.9)
        self.wait(37.4)

        self.ly.clear()

    # --- Scene 8: Order of an Element ---

    def scene8_properties(self):
        self.add_subcaption(
            "The order of an element g "
            "is the smallest positive integer n "
            "such that g to the n equals the identity. "
            "In Z6, the element 2 has order 3, "
            "because 2 plus 2 plus 2 equals 6, which is 0 mod 6. "
            "The element 1 has order 6. "
            "The order of g equals the size of the subgroup generated by g. "
            "This is a powerful connection between elements and subgroups. "
            "Also, if G is cyclic of order n, "
            "then for each divisor d of n, "
            "there is exactly one subgroup of order d. "
            "This is the divisor-counting theorem for cyclic groups.",
            duration=38.4,
        )

        title = self.ly.title("Order of an Element")

        defn = MathTex(
            r"\text{Order of } g = \min\{n > 0 : g^n = e\}",
            color=PRIMARY, font_size=30,
        )
        self.ly.safe_place(defn, anchor=title, direction=DOWN, buff=0.5)
        self.play(Write(defn), run_time=NORMAL)
        self.wait(0.2)

        ex_title = MathTex(
            r"\text{In } \mathbb{Z}_6:",
            color=WHITE, font_size=28,
        )
        self.ly.safe_place(ex_title, anchor=defn, direction=DOWN, buff=0.5)
        self.play(Write(ex_title), run_time=FAST)
        self.wait(0.15)

        examples = [
            MathTex(r"\text{ord}(1) = 6:\;\; 1+1+1+1+1+1 = 6 \equiv 0", color=SECONDARY, font_size=26),
            MathTex(r"\text{ord}(2) = 3:\;\; 2+2+2 = 6 \equiv 0", color=ACCENT, font_size=26),
            MathTex(r"\text{ord}(3) = 2:\;\; 3+3 = 6 \equiv 0", color=WHITE, font_size=26),
        ]

        prev = ex_title
        for ex in examples:
            self.ly.safe_place(ex, anchor=prev, direction=DOWN, buff=0.35)
            self.play(Write(ex), run_time=NORMAL)
            self.wait(0.2)
            prev = ex

        # pacing: extends previous caption slot (seg#7 natural 38.4s, slot 14.60s -> 48.00s, Δ=33.4)
        self.wait(33.7)
        self.ly.clear()

        title2 = self.ly.title("Key Theorem")

        theorem = MathTex(
            r"|\langle g \rangle| = \text{ord}(g)",
            color=ACCENT, font_size=34,
        )
        self.ly.safe_place(theorem, anchor=title2, direction=DOWN, buff=0.6)
        self.play(Write(theorem), run_time=NORMAL)
        self.wait(0.2)

        boxed = SurroundingRectangle(theorem, color=ACCENT, buff=0.2, stroke_width=2)
        self.play(Create(boxed), run_time=FAST)
        self.wait(0.2)

        meaning = Text(
            "The subgroup generated by g has the same size as the order of g",
            font_size=BODY_SIZE, color=WHITE, font=SANS,
        )
        self.ly.safe_place(meaning, anchor=theorem, direction=DOWN, buff=0.5)
        self.play(FadeIn(meaning, shift=LEFT * 0.15), run_time=FAST)
        self.wait(0.3)

        corollary = Text(
            "For cyclic G of order n: each divisor d of n",
            font_size=BODY_SIZE, color=PRIMARY, font=SANS,
        )
        self.ly.safe_place(corollary, anchor=meaning, direction=DOWN, buff=0.5)
        self.play(FadeIn(corollary, shift=LEFT * 0.15), run_time=FAST)
        self.wait(0.15)

        corollary2 = Text(
            "gives EXACTLY ONE subgroup of order d.",
            font_size=BODY_SIZE, color=PRIMARY, font=SANS, weight=BOLD,
        )
        self.ly.safe_place(corollary2, anchor=corollary, direction=DOWN, buff=0.3)
        self.play(FadeIn(corollary2, scale=1.05), run_time=FAST)
        self.wait(0.5)

        self.ly.clear()

    # --- Scene 9: Summary ---

    def scene9_summary(self):
        self.add_subcaption(
            "Let us recap. "
            "A subgroup is a subset of a group that is itself a group. "
            "The subgroup test lets us verify a subset is a subgroup "
            "with just one condition. "
            "A cyclic group is generated by a single element. "
            "Every cyclic group is abelian. "
            "Every subgroup of a cyclic group is cyclic. "
            "And the subgroups of a cyclic group of order n "
            "correspond one-to-one with the divisors of n. "
            "These are foundational results "
            "that we will build on when we study permutations and Lagrange's theorem. "
            "Thanks for watching!",
            duration=32.6,
        )

        title = self.ly.title("Summary")

        takeaways = [
            Text("1. Subgroup: subset that is itself a group", font_size=BODY_SIZE, color=PRIMARY, font=SANS),
            Text("2. Subgroup test: a*b^{-1} in H", font_size=BODY_SIZE, color=SECONDARY, font=SANS),
            Text("3. Cyclic group: generated by one element", font_size=BODY_SIZE, color=ACCENT, font=SANS),
            Text("4. Every cyclic group is abelian", font_size=BODY_SIZE, color=RED, font=SANS),
            Text("5. Subgroups of cyclic G correspond to divisors of |G|", font_size=BODY_SIZE, color=WHITE, font=SANS),
        ]

        self.ly.progressive_reveal(takeaways, start_from=title, run_time=0.6)
        self.wait(0.3)

        closing = Text(
            "You now understand subgroups and cyclic groups!",
            font_size=HEADING_SIZE, color=WHITE, font=SANS, weight=BOLD,
        )
        self.ly.safe_place(closing, anchor=title, direction=DOWN, buff=-3.2)
        clamp_position(closing)
        self.play(FadeIn(closing, scale=1.05), run_time=NORMAL)
        # pacing: extends previous caption slot (seg#8 natural 32.6s, slot 15.73s -> 40.83s, Δ=25.1)
        self.wait(25.6)

        play_outro(self, "Subgroups and Cyclic Groups", "Abstract Algebra I")
